TEA.Web/Areas/Backend/Controllers/EtapaController.cs
namespace TEA.Web.Areas.Backend.Controllers
{
    using System.Web.Mvc;
    using System.Linq;
    using TEA.Contratos;
    using TEA.Web.ViewsModel.Etapa;
    using TEA.Entidades.Negocio.Etapa;
    using PagedList;
    using TEA.Entidades.Negocio.Nivel;
    using System.Web;
    using System;
    using System.IO;
    using TEA.Entidades.Negocio.Diagnostico;
    using TEA.Entidades.Negocio.Respuestas;
    using System.Collections.Generic;
    using TEA.Entidades.Negocio.TipoDiagnostico;

    public class EtapaController : Controller
    {
        public IServicioEtapa ServicioEtapa;
        public IServicioNivel ServicioNivel;
        public IServicioDiagnostico ServicioDiagnostico;
        public IServicioRespuesta ServicioRespuesta;
        public IServicioTipoDiagnostico ServicioTipoDiagnostico;

        public EtapaController(IServicioEtapa ServicioEtapa, IServicioNivel ServicioNivel, IServicioDiagnostico ServicioDiagnostico, IServicioRespuesta ServicioRespuesta, IServicioTipoDiagnostico ServicioTipoDiagnostico)
        {
            this.ServicioEtapa = ServicioEtapa;
            this.ServicioNivel = ServicioNivel;
            this.ServicioDiagnostico = ServicioDiagnostico;
            this.ServicioRespuesta = ServicioRespuesta;
            this.ServicioTipoDiagnostico = ServicioTipoDiagnostico;
        }
        //
        // GET: /Etapa/
        public ActionResult Index(IndexVM model)
        {
            model.CurrentSort = model.SortOrder;
            model.NombreSortParm = model.SortOrder == "nombre" ? "nombre_desc" : "nombre";
            model.OrdenSortParm = model.SortOrder == "orden" ? "orden_desc" : "orden";
            model.FiltroTexto = model.BuscarTexto;

            var etapas = this.ServicioEtapa.ObtenerEtapas(new ObtenerEtapasRequest() { Orden = model.SortOrder, FiltroTexto = model.FiltroTexto, FiltroIdTipoDiagnostico = model.FiltroIdTipoDiagnostico, FiltroIdDiagnostico = model.FiltroIdDiagnostico, FiltroIdNivel = model.FiltroIdNivel });

            int pageSize = 10;
            int pageNumber = (model.Page ?? 1);

            var tipoDiagnosticos = this.ServicioTipoDiagnostico.ObtenerTipoDiagnosticos(new ObtenerTipoDiagnosticosRequest()).TipoDiagnostico;
            ViewBag.ListaTipoDiagnosticos = new SelectList(tipoDiagnosticos, "Id", "Nombre", model.FiltroIdTipoDiagnostico);

            var diagnosticos = this.ServicioDiagnostico.ObtenerDiagnosticos(new ObtenerDiagnosticosRequest() { FiltroIdTipoDiagnostico = model.FiltroIdTipoDiagnostico }).Diagnosticos;
            ViewBag.ListaDiagnosticos = new SelectList(diagnosticos, "Id", "Nombre", model.FiltroIdDiagnostico);

            var niveles = this.ServicioNivel.ObtenerNiveles(new ObtenerNivelesRequest() { FiltroIdTipoDiagnostico = model.FiltroIdTipoDiagnostico, FiltroIdDiagnostico = model.FiltroIdDiagnostico }).Niveles;
            ViewBag.ListaNiveles = new SelectList(niveles, "Id", "Nombre", model.FiltroIdNivel);

            model.Etapas = etapas.Etapas.ToPagedList(pageNumber, pageSize);
            return View(model);
        }

        public ActionResult Create()
        {
            var diagnosticos = this.ServicioDiagnostico.ObtenerDiagnosticos(new ObtenerDiagnosticosRequest()).Diagnosticos;
            ViewBag.ListaDiagnosticos = new SelectList(diagnosticos, "Id", "Nombre");
            ViewBag.ListaNiveles = new SelectList(Enumerable.Empty<SelectListItem>());

            var model = new GuardarEtapaRequest();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //public ActionResult Create(GuardarEtapaRequest request, HttpPostedFileBase[] files, bool Correcto, bool Fondo)
        public ActionResult Create(GuardarEtapaRequest request)
        {
            //HttpPostedFileBase myFile = Request.Files["files"];
            if (ModelState.IsValid)
            {
                var model = this.ServicioEtapa.GuardarEtapa(request);
                return RedirectToAction("Index");
            }

            var diagnosticos = this.ServicioDiagnostico.ObtenerDiagnosticos(new ObtenerDiagnosticosRequest()).Diagnosticos;
            var niveles = this.ServicioNivel.ObtenerNivelesPorDiagnostico(new ObtenerNivelesRequest() { IdDiagnostico = request.Etapa.IdDiagnostico }).Niveles;

            ViewBag.ListaDiagnosticos = new SelectList(diagnosticos, "Id", "Nombre", request.Etapa.IdDiagnostico);
            ViewBag.ListaNiveles = new SelectList(niveles, "Id", "Nombre", request.Etapa.IdNivel);
            return View(request);
        }

        public ActionResult Edit(int id)
        {
            var etapa = this.ServicioEtapa.ObtenerEtapaPorId(new ObtenerEtapaRequest() { IdEtapa = id });
            var model = new GuardarEtapaRequest() { Etapa = etapa.Etapa };
            var diagnosticos = this.ServicioDiagnostico.ObtenerDiagnosticos(new ObtenerDiagnosticosRequest()).Diagnosticos;
            var niveles = this.ServicioNivel.ObtenerNivelesPorDiagnostico(new ObtenerNivelesRequest() { IdDiagnostico = model.Etapa.IdDiagnostico }).Niveles;

            ViewBag.ListaDiagnosticos = new SelectList(diagnosticos, "Id", "Nombre", model.Etapa.IdDiagnostico);
            ViewBag.ListaNiveles = new SelectList(niveles, "Id", "Nombre", model.Etapa.IdNivel);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GuardarEtapaRequest request)
        {
            if (ModelState.IsValid)
            {
                var model = this.ServicioEtapa.GuardarEtapa(request);
                return RedirectToAction("Index");
            }

            var diagnosticos = this.ServicioDiagnostico.ObtenerDiagnosticos(new ObtenerDiagnosticosRequest()).Diagnosticos;
            var niveles = this.ServicioNivel.ObtenerNivelesPorDiagnostico(new ObtenerNivelesRequest() { IdDiagnostico = request.Etapa.IdDiagnostico }).Niveles;

            ViewBag.ListaDiagnosticos = new SelectList(diagnosticos, "Id", "Nombre", request.Etapa.IdDiagnostico);
            ViewBag.ListaNiveles = new SelectList(niveles, "Id", "Nombre", request.Etapa.IdNivel);
            return View(request);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var eliminar = this.ServicioEtapa.EliminarEtapa(new EliminarEtapaRequest() { IdEtapa = id });

            if (!eliminar.ValidarResponse.Valido)
            {
                var error = eliminar.ValidarResponse.Errores.First();
                return Json(new { resultado = false, clave = error.Key, valor = error.Value });
            }
            return Json(new { resultado = true, clave = "Clave exitosa", valor = "Valor exitoso" });
        }


        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ObtenerNivelesPorDiagnostico(int idDiagnostico)
        {
            var niveles = this.ServicioNivel.ObtenerNivelesPorDiagnostico(new ObtenerNivelesRequest() { IdDiagnostico = idDiagnostico }).Niveles;
            return Json(niveles, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SubirArchivo(int id)
        {
            Respuesta respuesta = new Respuesta();
            var etapa = this.ServicioEtapa.ObtenerEtapaPorId(new ObtenerEtapaRequest() { IdEtapa = id }).Etapa;
            respuesta.IdEtapa = etapa.Id;

            var model = new GuardarRespuestaRequest()
            {
                Respuesta = respuesta,
                IdDiagnostico = etapa.IdDiagnostico,
                IdNivel = etapa.IdNivel,
                NombreDiagnostico = etapa.NombreDiagnostico,
                NombreEtapa = etapa.Nombre,
                NombreNivel = etapa.NombreNivel,
                TituloEtapa = etapa.Titulo,
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult SubirArchivo(GuardarRespuestaRequest request, HttpPostedFileBase MyFile)
        {
            HttpPostedFileBase myFile = Request.Files["file"];
            bool isUploaded = false;
            string message = "File upload failed";

            if (myFile != null && myFile.ContentLength != 0)
            {
                string pathForSaving = Server.MapPath("~/Etapas/Imagenes");
                //string pathForSaving = Server.MapPath("~/Etapa/SubirArchivo");

                var virtualPath = Url.Content(string.Format("{0}\\{1}", pathForSaving, myFile.FileName));

                if (this.CreateFolderIfNeeded(pathForSaving))
                {
                    try
                    {
                        myFile.SaveAs(Path.Combine(pathForSaving, myFile.FileName));
                        request.Respuesta.NombreImagen = myFile.FileName;

                        int idRespuesta = this.ServicioRespuesta.GuardarRespuesta(request).IdRespuesta;

                        isUploaded = true;
                        return Json(new
                        {
                            files = new[] { 
                                new {
                                    idRespuesta = idRespuesta,
                                    imgUrl = virtualPath,
                                    name = myFile.FileName,
                                    size = myFile.ContentLength, 
                                    url = "Delete", 
                                    thumbnailUrl = myFile.FileName,
                                    deleteUrl = @"\\Etapas\\Imagenes" + "\\" + myFile.FileName,
                                    deleteType = "DELETE" 
                                }
                            }
                        }, "text/html");
                    }
                    catch (Exception ex)
                    {
                        return Json(new
                        {
                            files = new[] { 
                                new {
                                    error = "Erorr al subir el archivo",
                                    name = myFile.FileName,

TEA.Web/Areas/Backend/Views/Etapa/Create.cshtml
@model TEA.Entidades.Negocio.Etapa.GuardarEtapaRequest

@{
    ViewBag.Title = "Crear";
}

<div class="block-a">
    @using (Html.BeginForm("Create", "Etapa", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />

            @Html.ValidationSummary(true)

            <div class="panel panel-primary">
                <div class="panel-heading">Crear Etapa</div>
                <div class="panel-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.IdDiagnostico, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Etapa.IdDiagnostico, ViewBag.ListaDiagnosticos as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.IdDiagnostico)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.IdNivel, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Etapa.IdNivel, ViewBag.ListaNiveles as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.IdNivel)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.Nombre, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Etapa.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.Titulo, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Etapa.Titulo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.Titulo)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.Orden, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Etapa.Orden, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.Orden)
                        </div>
                    </div>
                
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Aceptar</button>
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>
    }

</div>


<script type="text/javascript">
    $(document).ready(function () {

        var selectedItem = $("#Etapa_IdDiagnostico").val();
        if (selectedItem == "") {
            LimpiarNivel();
        }

        $("#Etapa_IdDiagnostico").change(function () {
            var selectedItem = $(this).val();
            if (selectedItem != "") {
                var nivel = $("#Etapa_IdNivel");
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: "/Etapa/ObtenerNivelesPorDiagnostico",
                    data: { "idDiagnostico": selectedItem },
                    success: function (data) {
                        nivel.html('<option value="">Seleccione...</option>');
                        $.each(data, function (i, datos) {
                            nivel.append($('<option></option>').val(datos.Id).html(datos.Nombre));
                        });
                        nivel.removeAttr("disabled", "disabled");
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Error.');
                    }
                });
            }
            else {
                LimpiarNivel();
            }
        });

        $("#Etapa_IdNivel").change(function () {
            var selectedItem = $(this).val();
            debugger;
            if (selectedItem != "") {
                var orden = $("#Etapa_Orden");
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: "/Etapa/ObtenerUltimoOrden",
                    data: { "idNivel": selectedItem },
                    success: function (data) {
                        orden.val(data.orden);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Error.');
                    }
                });
            }
            else {
                LimpiarOrden();
            }
        });

    });

    function LimpiarNivel() {
        var nivel = $("#Etapa_IdNivel");
        nivel.html('<option value="">Seleccione...</option>');
        nivel.attr("disabled", "disabled");
    }

    function LimpiarOrden() {
        var orden = $("#Etapa_Orden");
        nivel.val("");
    }
</script>

TEA.Web/Areas/Backend/Views/Etapa/Edit.cshtml
@model TEA.Entidades.Negocio.Etapa.GuardarEtapaRequest

@{
    ViewBag.Title = "Editar";
}

<div class="block-a">
    @using (Html.BeginForm("Edit", "Etapa", new { }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Etapa.Id)

        <div class="form-horizontal">

            <hr />

            @Html.ValidationSummary(true)

            <div class="panel panel-primary">
                <div class="panel-heading">Editar Nivel</div>
                <div class="panel-body">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.IdDiagnostico, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Etapa.IdDiagnostico, ViewBag.ListaDiagnosticos as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.IdDiagnostico)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.IdNivel, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Etapa.IdNivel, ViewBag.ListaNiveles as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.IdNivel)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.Nombre, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Etapa.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.Titulo, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Etapa.Titulo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.Titulo)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Etapa.Orden, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Etapa.Orden, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Etapa.Orden)
                        </div>
                    </div>

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Aceptar</button>
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>
    }

</div>

<script type="text/javascript">
    $(document).ready(function () {

        var selectedItem = $("#Etapa_IdDiagnostico").val();
        if (selectedItem == "") {
            LimpiarNivel();
        }

        $("#Etapa_IdDiagnostico").change(function () {
            var selectedItem = $(this).val();
            if (selectedItem != "") {
                var nivel = $("#Etapa_IdNivel");
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: "/Etapa/ObtenerNivelesPorDiagnostico",
                    data: { "idDiagnostico": selectedItem },
                    success: function (data) {
                        nivel.html('<option value="">Seleccione...</option>');
                        $.each(data, function (i, datos) {
                            nivel.append($('<option></option>').val(datos.Id).html(datos.Nombre));
                        });
                        nivel.removeAttr("disabled", "disabled");
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                        alert('Error.');
                    }
                });
            }
            else {
                LimpiarNivel();
            }
        });

    });

    function LimpiarNivel() {
        var nivel = $("#Etapa_IdNivel");
        nivel.html('<option value="">Seleccione...</option>');
        nivel.attr("disabled", "disabled");
    }
</script>

TEA.Web/Areas/Backend/Views/Etapa/Index.cshtml
@model TEA.Web.ViewsModel.Etapa.IndexVM
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Etapa</li>
</ol>

@using (Html.BeginForm("Index", "Etapa", FormMethod.Get))
{

    <div class="panel panel-primary">
        <div class="panel-heading">Filtrar Diagnóstico</div>
        <div class="panel-body">
            <div class="row form-group">
                <div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.FiltroIdTipoDiagnostico, new { @class = "control-label col-md-5", })
                        <div class="col-md-7">
                            @Html.DropDownListFor(model => model.FiltroIdTipoDiagnostico, ViewBag.ListaTipoDiagnosticos as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FiltroIdTipoDiagnostico)
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.FiltroIdDiagnostico, new { @class = "control-label col-md-4", })
                        <div class="col-md-8">
                            @Html.DropDownListFor(model => model.FiltroIdDiagnostico, ViewBag.ListaDiagnosticos as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FiltroIdDiagnostico)
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        @Html.LabelFor(model => model.FiltroIdNivel, new { @class = "control-label col-md-4", })
                        <div class="col-md-8">
                            @Html.DropDownListFor(model => model.FiltroIdNivel, ViewBag.ListaNiveles as SelectList, "Seleccione...", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.FiltroIdNivel)
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="form-group">
                        @Html.LabelFor(model => model.BuscarTexto, new { @class = "control-label col-md-3", })
                        <div class="col-md-9">
                            @Html.TextBoxFor(model => model.BuscarTexto, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.BuscarTexto)
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <button type="submit" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
                </div>
            </div>
        </div>
    </div>

    <table class="table table-hover" style="background-color:white">
        <thead>
            <tr>
                <th class="@(Model.NombreSortParm.Contains("desc") ? "dropup" : "")">
                    @Html.ActionLink("Etapa", "Index", "Etapa", new { sortOrder = Model.NombreSortParm, filtroTexto = Model.FiltroTexto, filtroIdTipoDiagnostico = Model.FiltroIdTipoDiagnostico, filtroIdDiagnostico = Model.FiltroIdDiagnostico, filtroIdNivel = Model.FiltroIdNivel }, null) <span class='caret'></span>
                </th>
                <th>
                    Diagnóstico
                </th>
                <th>
                    Nivel
                </th>
                <th class="@(Model.OrdenSortParm.Contains("desc") ? "dropup" : "")">
                    @Html.ActionLink("Orden", "Index", "Etapa", new { sortOrder = Model.OrdenSortParm, filtroTexto = Model.FiltroTexto, filtroIdTipoDiagnostico = Model.FiltroIdTipoDiagnostico, filtroIdDiagnostico = Model.FiltroIdDiagnostico, filtroIdNivel = Model.FiltroIdNivel }, null) <span class='caret'></span>
                </th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Etapas)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreDiagnostico)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NombreNivel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Orden)
                    </td>
                    <td>
                        <a href="@Url.Action("Edit", "Etapa", new { id = item.Id })"><i class="btn btn-primary btn-md  glyphicon glyphicon-pencil"></i></a>
                        <a href="@Url.Action("Details", "Etapa", new { id = item.Id })"><i class="btn btn-info btn-md glyphicon glyphicon-search"></i></a>
                        <a href="@Url.Action("SubirArchivo", "Etapa", new { id = item.Id })"><i class="btn btn-success btn-md glyphicon glyphicon-picture"></i></a>
                        <a data-toggle="modal" data-target="#myModal" data-id="@item.Id"><i class="btn btn-danger btn-md glyphicon glyphicon-trash delete"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="row">
        <div class="col-md-12 text-right">
            @{
            var pagedListOptions = PagedListRenderOptions.OnlyShowFivePagesAtATime;
            pagedListOptions.DisplayLinkToLastPage = pagedListOptions.DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded;
            pagedListOptions.UlElementClasses = new List<string>() { "pagination", "pagination-sm" };
            }
            @Html.PagedListPager(Model.Etapas, page => Url.Action("Index", new
         {
             page,
             sortOrder = Model.CurrentSort,
             filtroTexto = Model.FiltroTexto,
             filtroIdTipoDiagnostico = Model.FiltroIdTipoDiagnostico,
             filtroIdDiagnostico = Model.FiltroIdDiagnostico,
             filtroIdNivel = Model.FiltroIdNivel,
         }), pagedListOptions)
        </div>
    </div>
}

@Html.Partial("_ConfirmacionEliminar")

<div class="top-options pull-right">
    @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-default " })
</div>
<br />
<br />

<script type="text/javascript">
    $(function () {

        var id = "";
        $(".delete").click(function (e) {
            debugger;
            id = $(this).parent().data('id');
            var nombreEtapa = $(this).parent().parent().parent().children('td:first').text()
            $('.cuerpoConfirmacion').html(nombreEtapa);
        });

        $(".guardarConfirmacion").click(function (e) {
            debugger;

            if (id != "") {
                $.ajax({
                    url: '/Etapa/Delete',
                    type: 'POST',
                    data: { id: id },
                    success: function (data) {
                        if (data.resultado) {
                            $('#myModal').modal('hide')
                            $('body').removeClass('modal-open');
                            $('.modal-backdrop').remove();
                            alert("Clave: " + data.clave + " Valor: " + data.valor);
                        }
                        else {
                            alert("Clave: " + data.clave + " Valor: " + data.valor);
                        };
                    },
                    error: function (e) {
                    }
                });
            }
            id = "";

        });

    });
</script>