TEA.Web/Areas/Backend/Controllers/UsuariosController.cs
namespace TEA.Web.Areas.Backend.Controllers
{
    using System.Web.Mvc;
    using System.Linq;
    using TEA.Entidades.Negocio.Usuario;
    using System;
    using TEA.Contratos;
    using TEA.Web.ViewsModel.Usuario;
    using PagedList;
    using Microsoft.AspNet.Identity;
    using System.Security.Claims;
    using TEA.Web.Infrastucture.Security;
    using TEA.Web.Filters;

    //[Authorize(Roles = UserRoles.Administrador)]
    //[CustomAuthenticationAttribute(Roles = UserRoles.Administrador)]
    [RouteArea("Backend")]
    public class UsuariosController : Controller
    {
        public IServicioUsuario ServicioUsuario;

        public UsuariosController(IServicioUsuario servicioUsuario)
        {
            this.ServicioUsuario = servicioUsuario;
        }

        //
        // GET: /Usuarios/
        public ActionResult Index(IndexVM model)
        {
            model.CurrentSort = model.SortOrder;
            model.NombreSortParm = model.SortOrder == "nombre" ? "nombre_desc" : "nombre";

            var usuarioActual = (CustomIdentity)User.Identity;
            if (usuarioActual != null)
            {
                model.IdUsuarioPadre = usuarioActual.Id;
            }

            var usuarios = this.ServicioUsuario.ObtenerUsuarios(new ObtenerUsuariosRequest() { Orden = model.SortOrder, IdUsuarioPadre = model.IdUsuarioPadre }).Usuarios;

            int pageSize = 10;
            int pageNumber = (model.Page ?? 1);

            model.Usuarios = usuarios.ToPagedList(pageNumber, pageSize);
            return View(model);
        }

        public ActionResult Create()
        {
            GuardarUsuarioRequest request = new GuardarUsuarioRequest();
            Usuario usuario = new Usuario()
            {
                Eliminado = false,
                FechaNacimiento = DateTime.Now,
            };
            request.Usuario = usuario;

            return View(request);
        }

        [HttpPost]
        public ActionResult Create(GuardarUsuarioRequest model)
        {
            var usuarioActual = (CustomIdentity)User.Identity;
            if (usuarioActual != null)
            {
                model.Usuario.IdUsuarioPadre = usuarioActual.Id;
            }

            if (ModelState.IsValid)
            {
                var user = this.ServicioUsuario.ObtenerUsuarioPorUserName(new ObtenerUsuarioRequest() { UserName = model.Usuario.UserName });

                if (user != null && user.Usuario != null)
                {
                    ModelState.AddModelError("Username", "El nombre de usuario ya existe");
                    return View(model);
                }

                this.ServicioUsuario.GuardarUsuario(model);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var usuario = this.ServicioUsuario.ObtenerUsuarioPorId(new ObtenerUsuarioRequest() { IdUsuario = id }).Usuario;
            
            GuardarUsuarioRequest request = new GuardarUsuarioRequest();
            request.Usuario = usuario;

            return View(request);
        }

        [HttpPost]
        public ActionResult Edit(GuardarUsuarioRequest model)
        {

            if (ModelState.IsValid)
            {
                var user = this.ServicioUsuario.ObtenerUsuarioPorUserName(new ObtenerUsuarioRequest() { UserName = model.Usuario.UserName });

                if (user != null && user.Usuario != null)
                {
                    ModelState.AddModelError("Username", "El nombre de usuario ya existe");
                    return View(model);
                }

                this.ServicioUsuario.GuardarUsuario(model);

                return RedirectToAction("Index", "Home");
            }

            return View(model);
        }
	}
}

TEA.Web/Areas/Backend/Views/Usuarios/Create.cshtml
@model TEA.Entidades.Negocio.Usuario.GuardarUsuarioRequest

@{
    ViewBag.Title = "Crear Usuario";
}

<div class="block-a">
    @using (Html.BeginForm("Create", "Usuarios", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />

            @Html.ValidationSummary(true)

            <div class="panel panel-primary">
                <div class="panel-heading">Crear usuario</div>
                <div class="panel-body">

                    @Html.HiddenFor(model => model.Usuario.FechaNacimiento)


                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.UserName, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.UserName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.UserName)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.Password, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.Password)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.RePassword, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.RePassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.RePassword)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.Nombre, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.DNI, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.DNI, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.DNI)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.EsAdmin, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.Usuario.EsAdmin)
                            @Html.ValidationMessageFor(model => model.Usuario.EsAdmin)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.EsUsuario, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.Usuario.EsUsuario)
                            @Html.ValidationMessageFor(model => model.Usuario.EsUsuario)
                        </div>
                    </div>

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Aceptar</button>
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>
    }

</div>

TEA.Web/Areas/Backend/Views/Usuarios/Edit.cshtml
@model TEA.Entidades.Negocio.Usuario.GuardarUsuarioRequest

@{
    ViewBag.Title = "Editar Usuario";
}

<div class="block-a">
    @using (Html.BeginForm("Edit", "Usuarios", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Usuario.Id)
        @Html.HiddenFor(model => model.Usuario.IdUsuarioPadre)

        <div class="form-horizontal">

            <hr />

            @Html.ValidationSummary(true)

            <div class="panel panel-primary">
                <div class="panel-heading">Editar usuario</div>
                <div class="panel-body">

                    @Html.HiddenFor(model => model.Usuario.FechaNacimiento)


                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.UserName, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.UserName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.UserName)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.Password, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.Password)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.RePassword, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.RePassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.RePassword)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.Nombre, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.DNI, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Usuario.DNI, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Usuario.DNI)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.EsAdmin, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.Usuario.EsAdmin)
                            @Html.ValidationMessageFor(model => model.Usuario.EsAdmin)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario.EsUsuario, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.CheckBoxFor(model => model.Usuario.EsUsuario)
                            @Html.ValidationMessageFor(model => model.Usuario.EsUsuario)
                        </div>
                    </div>

                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Aceptar</button>
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

        </div>
    }

</div>

TEA.Web/Areas/Backend/Views/Usuarios/Index.cshtml
@model TEA.Web.ViewsModel.Usuario.IndexVM
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<ol class="breadcrumb">
    <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Usuario</li>
</ol>

<div class="panel panel-primary">
    <div class="panel-heading">Lista de Usuarios</div>
    <div class="block-a table-responsive ">
        <div class="panel-heading">
            <table class="table panel-primary">
                <thead>
                    <tr>
                        <th class="@(Model.NombreSortParm.Contains("desc") ? "dropup" : "")">
                            @Html.ActionLink("Usuario", "Index", "Usuarios", new { sortOrder = Model.NombreSortParm }) <span class='caret'></span>
                        </th>
                        <th>
                            Id
                        </th>
                        <th>
                            Username
                        </th>
                        <th>
                            DNI
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Usuarios)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DNI)
                            </td>
                            <td>
                                <a href="@Url.Action("Edit", "Usuarios", new { id = item.Id })"><i class="btn btn-primary btn-md  glyphicon glyphicon-pencil"></i></a>
                                <a href="@Url.Action("Details", "Usuarios", new { id = item.Id })"><i class="btn btn-info btn-md glyphicon glyphicon-search"></i></a>
                                <a data-toggle="modal" data-target="#myModal" data-id="@item.Id"><i class="btn btn-danger btn-md glyphicon glyphicon-trash delete"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>


        <div class="row">
            <div class="col-md-12 text-right">
                @{
                    var pagedListOptions = PagedListRenderOptions.OnlyShowFivePagesAtATime;
                    pagedListOptions.DisplayLinkToLastPage = pagedListOptions.DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded;
                    pagedListOptions.UlElementClasses = new List<string>() { "pagination", "pagination-sm" };
                }
                @Html.PagedListPager(Model.Usuarios, page => Url.Action("Index", new
         {
             page,
             sortOrder = Model.CurrentSort
         }), pagedListOptions)
            </div>
        </div>
    </div>
</div>

@Html.Partial("_ConfirmacionEliminar")

<div class="top-options pull-right">
    @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-default " })
</div>
<br />
<br />

<script type="text/javascript">
    $(function () {

        var id = "";
        $(".delete").click(function (e) {
            debugger;
            id = $(this).parent().data('id');
            var nombre = $(this).parent().parent().parent().children('td:first').text()
            $('.cuerpoConfirmacion').html(nombre);
        });

        $(".guardarConfirmacion").click(function (e) {
            debugger;

            if (id != "") {
                $.ajax({
                    url: '/Usuarios/Delete',
                    type: 'POST',
                    data: { id: id },
                    success: function (data) {
                        if (data.resultado) {
                            $('#myModal').modal('hide')
                            $('body').removeClass('modal-open');
                            $('.modal-backdrop').remove();
                            alert("Clave: " + data.clave + " Valor: " + data.valor);
                        }
                        else {
                            alert("Clave: " + data.clave + " Valor: " + data.valor);
                        };
                    },
                    error: function (e) {
                    }
                });
            }
            id = "";

        });

    });
</script>