TEA.Web/Areas/Backend/Controllers/DiagnosticoController.cs
namespace TEA.Web.Areas.Backend.Controllers
{
    using System.Web.Mvc;
    using TEA.Contratos;
    using TEA.Entidades.Negocio.Diagnostico;
    using TEA.Web.ViewsModel.Diagnostico;
    using PagedList;
    using System.Linq;
    using TEA.Entidades.Negocio.TipoDiagnostico;
    using TEA.Entidades.Negocio.Usuario;
    using System;
    using System.Collections.Generic;
    using TEA.Web.Infrastucture.Security;

    //[Authorize(Roles = UserRoles.Administrador)]
    public class DiagnosticoController : Controller
    {
        public IServicioDiagnostico ServicioDiagnostico;
        public IServicioTipoDiagnostico ServicioTipoDiagnostico;
        public IServicioUsuario ServicioUsuario;

        public DiagnosticoController(IServicioDiagnostico ServicioDiagnostico, IServicioTipoDiagnostico ServicioTipoDiagnostico, IServicioUsuario ServicioUsuario)
        {
            this.ServicioDiagnostico = ServicioDiagnostico;
            this.ServicioTipoDiagnostico = ServicioTipoDiagnostico;
            this.ServicioUsuario = ServicioUsuario;
        }

        public ActionResult Index(IndexVM model)
        {
            model.CurrentSort = model.SortOrder;
            model.NombreSortParm = model.SortOrder == "nombre" ? "nombre_desc" : "nombre";
            model.FilteredText = model.SearchThisText;

            var niveles = this.ServicioDiagnostico.ObtenerDiagnosticos(new ObtenerDiagnosticosRequest() { Orden = model.SortOrder, FilteredText = model.FilteredText  });

            int pageSize = 10;
            int pageNumber = (model.Page ?? 1);

            model.Diagnosticos = niveles.Diagnosticos.ToPagedList(pageNumber, pageSize);
            return View(model);
        }

        public ActionResult Create()
        {
            var model = new GuardarDiagnosticoRequest();
            var tipoDiagnosticos = ServicioTipoDiagnostico.ObtenerTipoDiagnosticos(new ObtenerTipoDiagnosticosRequest()).TipoDiagnostico;
            var usuarioActual = (CustomIdentity)User.Identity;

            Diagnostico diagnostico = new Diagnostico()
            {
                IdUsuarioProfesional = usuarioActual != null ? usuarioActual.Id : (int?)null,
            };
            model.Diagnostico = diagnostico;
            //model.IdUsuarios = usuarioActual != null ? this.ServicioUsuario.ObtenerIdUsuarios(new ObtenerUsuariosRequest() { IdUsuarioPadre = usuarioActual.Id }).IdUsuarios : null;
            ViewBag.ListaTipoDiagnosticos = new SelectList(tipoDiagnosticos, "Id", "Nombre");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GuardarDiagnosticoRequest request)
        {
            
            if (ModelState.IsValid)
            {
                var model = this.ServicioDiagnostico.GuardarDiagnostico(request);
                //Obtener de vuelta el id del diagnostico que fue guardado
                //Llamar al servicio GuardarUsuarioDiagnostico, pasandole el IdDiagnostico y los Ids de los Usuarios.
                //request.IdDiagnostico = request.Diagnostico.Id; //Algo así, ver como obtener el id de diagnostico guardado
                request.IdDiagnostico = model.IdDiagnostico;
                var usuariosDiagnosticos = this.ServicioDiagnostico.GuardarUsuarioDiagnostico(request);
                
                return RedirectToAction("Index");
            }
            var tipoDiagnosticos = ServicioTipoDiagnostico.ObtenerTipoDiagnosticos(new ObtenerTipoDiagnosticosRequest()).TipoDiagnostico;
            ViewBag.ListaTipoDiagnosticos = new SelectList(tipoDiagnosticos, "Id", "Nombre", request.Diagnostico.IdTipoDiagnostico);
            return View(request);
        }

        public ActionResult Edit(int id)
        {
            var model = new GuardarDiagnosticoRequest();
            var diagnostico = this.ServicioDiagnostico.ObtenerDiagnosticoPorId(new ObtenerDiagnosticoRequest() { IdDiagnostico = id }).Diagnostico;
            var tipoDiagnosticos = ServicioTipoDiagnostico.ObtenerTipoDiagnosticos(new ObtenerTipoDiagnosticosRequest()).TipoDiagnostico;

            model.Diagnostico = diagnostico;
            model.IdUsuarios = this.ServicioUsuario.ObtenerIdUsuariosPorDiagnostico(new ObtenerUsuariosRequest() { IdDiagnostico = id }).IdUsuarios;
            ViewBag.ListaTipoDiagnosticos = new SelectList(tipoDiagnosticos, "Id", "Nombre", model.Diagnostico.IdTipoDiagnostico);

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GuardarDiagnosticoRequest request)
        {
            if (ModelState.IsValid)
            {
                request.Diagnostico.Eliminado = false;
                var model = this.ServicioDiagnostico.GuardarDiagnostico(request);
                request.IdDiagnostico = model.IdDiagnostico;
                var usuariosDiagnosticos = this.ServicioDiagnostico.GuardarUsuarioDiagnostico(request);
                return RedirectToAction("Index");
            }

            var tipoDiagnosticos = ServicioTipoDiagnostico.ObtenerTipoDiagnosticos(new ObtenerTipoDiagnosticosRequest()).TipoDiagnostico;
            ViewBag.ListaTipoDiagnosticos = new SelectList(tipoDiagnosticos, "Id", "Nombre", request.Diagnostico.IdTipoDiagnostico);
            return View(request);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var eliminar = this.ServicioDiagnostico.EliminarDiagnostico(new EliminarDiagnosticoRequest() { IdDiagnostico = id });
            
            if (!eliminar.ValidarResponse.Valido)
            {
                var error = eliminar.ValidarResponse.Errores.First();
                return Json(new { resultado = false, clave = error.Key, valor = error.Value });
            }
            return Json(new { resultado = true, clave = "Clave exitosa", valor = "Valor exitoso" });
        }

        
        [HttpGet]
        public virtual JsonResult ObtenerUsuariosPorProfesional()
        {
            var usuarioActual = (CustomIdentity)User.Identity;
            var usuarios = usuarioActual != null ? this.ServicioUsuario.ObtenerUsuarios(new ObtenerUsuariosRequest() { IdUsuarioPadre = usuarioActual.Id }).Usuarios : null;
            var usuariosJSON = new List<Object>();

            foreach (var u in usuarios)
            {
                usuariosJSON.Add(new
                {
                    IdUsuario = u.Id,
                    NombreUsuario = u.Nombre,
                });
            }

            return Json(usuariosJSON.ToArray(), JsonRequestBehavior.AllowGet);
        }
	}
}

TEA.Web/Areas/Backend/Views/Diagnostico/Create.cshtml
@model TEA.Entidades.Negocio.Diagnostico.GuardarDiagnosticoRequest

@{
    ViewBag.Title = "Create";
}

@*<link href="~/Content/selectivity/selectivity-full.css" rel="stylesheet" />
<script src="~/Scripts/Selectivity/selectivity-full.js"></script>*@
<h2>Crear Diangóstico</h2>
@*<ol class="breadcrumb">
    <li><a href="#"> Home</a></li>
    <li><a href="#"> Diagnóstico</a></li>
    <li class="active">Crear</li>
</ol>*@
<div class="block-a">
    
    @using (Html.BeginForm("Create", "Diagnostico", new { }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Diagnostico.IdUsuarioProfesional)

        <div class="form-horizontal">
                    
            <hr class="gris"/>

            @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Diagnostico.IdTipoDiagnostico, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Diagnostico.IdTipoDiagnostico, ViewBag.ListaTipoDiagnosticos as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Diagnostico.IdTipoDiagnostico)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Diagnostico.Nombre, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Diagnostico.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Diagnostico.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Diagnostico.Descripcion, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Diagnostico.Descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Diagnostico.Descripcion)
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-2" for="Usuarios">Usuarios</label>
                            <div class="col-md-10">
                                <p>
                                    <div id="example-2" class="selectivity-input example-input">
                                        <div class="selectivity-multiple-input-container" id="example2">
                                            <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" class="selectivity-multiple-input" placeholder="Type to search a city" style="width:100%;">
                                            <span class="selectivity-multiple-input selectivity-width-detector">Buscar Responsables</span>
                                            <div class="selectivity-clearfix">
                                            </div>
                                        </div>
                                    </div>
                                </p>
                            </div>
                    </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Aceptar</button>
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

            
        </div>
    }

</div>

<script type="text/javascript">
    
    $(document).ready(function(){
        
        //var listaDeUsuarios = @(Html.Raw(Json.Encode(Model.IdUsuarios)));
        Usuarios = ObtenerUsuarios();


        $('#example-2').selectivity({
            items: Usuarios,
            multiple: true,
            placeholder: 'Buscar Usuarios'
        });

        //Variable "listaDeUsuarios", es una lista de los Id de Usuarios que ya tiene el diagnóstico
        //if (listaDeUsuarios != null) {
        //    $.each(listaDeUsuarios, function (key, value) {
        //        $('#example-2').selectivity('add', value)
        //    });
        //}
    });

    ////Vuelve a llenar la lista de puestos.
    //function LlenarSelectivity(ListaPuestos) {
    //    $('#example-2').selectivity({
    //        items: ListaPuestos,
    //        multiple: true,
    //        placeholder: 'Buscar Puestos'
    //    });
    //}


    function ObtenerUsuarios() {
        var usuarios = [];
        $.ajax({
            type: "GET",
            async: false,
            url: "/Diagnostico/ObtenerUsuariosPorProfesional",
            success: function (data) {
                $.each(data, function (i, item) {
                    usuarios.push({
                        id: item.IdUsuario,
                        text: item.NombreUsuario,
                        idClassInput: "IdUsuarios",
                        nameInput: "IdUsuarios"
                    })
                });
            }
        });
        return usuarios;
    }
</script>

TEA.Web/Areas/Backend/Views/Diagnostico/Edit.cshtml
@model TEA.Entidades.Negocio.Diagnostico.GuardarDiagnosticoRequest

@{
    ViewBag.Title = "Edit";
}

<link href="~/Content/selectivity/selectivity-full.css" rel="stylesheet" />
<script src="~/Scripts/Selectivity/selectivity-full.js"></script>
<h2>Editar Diangóstico</h2>
<div class="block-a">
    @using (Html.BeginForm("Edit", "Diagnostico", new { }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Diagnostico.Id)
        @Html.HiddenFor(model => model.Diagnostico.IdUsuarioProfesional)

        <div class="form-horizontal">

            <hr class="gris" />

            @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.Diagnostico.IdTipoDiagnostico, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Diagnostico.IdTipoDiagnostico, ViewBag.ListaTipoDiagnosticos as SelectList, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Diagnostico.IdTipoDiagnostico)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Diagnostico.Nombre, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(model => model.Diagnostico.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Diagnostico.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Diagnostico.Descripcion, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(model => model.Diagnostico.Descripcion, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Diagnostico.Descripcion)
                        </div>
                    </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-ok"></span> Aceptar</button>
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
                </div>
            </div>

            <div class="form-group">
                <label>Usuarios</label>
                <p>
                    <div id="example-2" class="selectivity-input example-input">
                        <div class="selectivity-multiple-input-container" id="example2">
                            <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" class="selectivity-multiple-input" placeholder="Type to search a city" style="width:100%;">
                            <span class="selectivity-multiple-input selectivity-width-detector">Buscar Responsables</span>
                            <div class="selectivity-clearfix">
                            </div>
                        </div>
                    </div>
                </p>
            </div>

        </div>
    }

</div>

<script type="text/javascript">
    $(function(){
        var listaDeUsuarios = @(Html.Raw(Json.Encode(Model.IdUsuarios)));
        IdUsuarios = ObtenerUsuarios();


        $('#example-2').selectivity({
            items: IdUsuarios,
            multiple: true,
            placeholder: 'Buscar Usuarios'
        });

        //Variable "listaDeUsuarios", es una lista de los Id de Puestos definida en CreateOrEdit.html.
        if (listaDeUsuarios != null) {
            $.each(listaDeUsuarios, function (key, value) {
                $('#example-2').selectivity('add', value)
            });
        }
    });

    ////Vuelve a llenar la lista de puestos.
    //function LlenarSelectivity(ListaPuestos) {
    //    $('#example-2').selectivity({
    //        items: ListaPuestos,
    //        multiple: true,
    //        placeholder: 'Buscar Puestos'
    //    });
    //}

    function ObtenerUsuarios() {
        var usuarios = [];
        $.ajax({
            type: "GET",
            async: false,
            url: "/Diagnostico/ObtenerUsuariosPorProfesional",
            success: function (data) {
                $.each(data, function (i, item) {
                    usuarios.push({
                        id: item.IdUsuario,
                        text: item.NombreUsuario,
                        idClassInput: "IdUsuarios",
                        nameInput: "IdUsuarios"
                    })
                });
            }
        });
        return usuarios;
    }
</script>

TEA.Web/Areas/Backend/Views/Diagnostico/Index.cshtml
@model TEA.Web.ViewsModel.Diagnostico.IndexVM
@using PagedList.Mvc;
@{
    ViewBag.Title = "Index";
}

<h2>Listado Diagnósticos</h2>
<ol class="breadcrumb">
    <li><a href="/Home"><i class="fa fa-home"></i> Home</a></li>
    <li class="active">Diagnóstico</li>
</ol>
@using (Html.BeginForm("Index", "Diagnostico", FormMethod.Get))
{
    <div class="panel panel-primary">
        <div class="panel-heading">Filtrar Diagnóstico</div>
        <br />
        <div class="row">
            <div class="col-md-5">
                <div class="form-group">
                    @Html.LabelFor(model => model.SearchThisText, new { @class = "control-label col-md-3", })
                    <div class="col-md-9">
                        @Html.TextBoxFor(model => model.SearchThisText, new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.SearchThisText)
                    </div>
                </div>
            </div>
            <div class="col-md-7">
                <button type="submit" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-search"></span> Buscar</button>
            </div>
        </div>
        <br />
    </div>

    <table class="table table-hover" style="background-color:white">
        <thead>
            <tr>
                <th class="@(Model.NombreSortParm.Contains("desc") ? "dropup" : "")">
                    @Html.ActionLink("Diagnostico", "Index", "Diagnostico", new { SortOrder = Model.NombreSortParm, filteredText = Model.FilteredText }, null) <span class='caret'></span>
                </th>
                <th>
                    Tipo de Diagóstico
                </th>
                <th>
                    Acciones
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Diagnosticos)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NombreTipoDiagnostico)
            </td>
            <td>
                <a href="@Url.Action("Edit", "Diagnostico", new { id = item.Id })"><i class="btn btn-primary btn-md  glyphicon glyphicon-pencil"></i></a>
                <a href="@Url.Action("Details", "Diagnostico", new { id = item.Id })"><i class="btn btn-info btn-md glyphicon glyphicon-search"></i></a>
                <a data-toggle="modal" data-target="#myModal" data-id="@item.Id"><i class="btn btn-danger btn-md glyphicon glyphicon-trash delete"></i></a>
            </td>
        </tr>
        }
        </tbody>
    </table>

    <div class="row">
        <div class="col-md-12 text-right">
            @{
            var pagedListOptions = PagedListRenderOptions.OnlyShowFivePagesAtATime;
            pagedListOptions.DisplayLinkToLastPage = pagedListOptions.DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded;
            pagedListOptions.UlElementClasses = new List<string>() { "pagination", "pagination-sm" };
            }
            @Html.PagedListPager(Model.Diagnosticos, page => Url.Action("Index", new
    {
        page,
        sortOrder = Model.CurrentSort,
        filteredText = Model.FilteredText,
    }), pagedListOptions)
        </div>
    </div>
}


@Html.Partial("_ConfirmacionEliminar")

<div class="top-options pull-right">
    @Html.ActionLink("Nuevo", "Create", null, new { @class = "btn btn-default " })
</div>
<br />
<br />

<script type="text/javascript">
    $(function () {

        var id = "";
        $(".delete").click(function (e) {
            debugger;
            id = $(this).parent().data('id');
            var nombreDaignositco = $(this).parent().parent().parent().children('td:first').text()
            $('.cuerpoConfirmacion').html(nombreDaignositco);
        });

        $(".guardarConfirmacion").click(function (e) {
            debugger;

            if (id != "") {
                $.ajax({
                    url: '/Diagnostico/Delete',
                    type: 'POST',
                    data: { id: id },
                    success: function (data) {
                        if (data.resultado) {
                            $('#myModal').modal('hide')
                            $('body').removeClass('modal-open');
                            $('.modal-backdrop').remove();
                            alert("Clave: " + data.clave + " Valor: " + data.valor);
                        }
                        else {
                            alert("Clave: " + data.clave + " Valor: " + data.valor);
                        };
                    },
                    error: function (e) {
                        //called when there is an error
                        //console.log(e.message);
                    }
                });
            }

            id = "";

        });

    });
</script>